version: 2

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              # See https://developer.chrome.com/apps/manifest/version for valid Chrome version strings
              # We've decided to enforce semver.
              only: /^[0-9]+(\.[0-9]+){2}$/

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Setup GitHub user
          command: |
            git config user.email "circleci@returntocorp.com"
            git config user.name "circleci"
      - run:
          name: Install yarn deps and build
          command: |
            yarn
            yarn build
      - run:
          name: Update manifest version
          command: |
            jq '.name = "R2C Beta"' build/manifest.json > build/manifest-tmp.json
            jq '.browser_action.default_title = "R2C Beta"' build/manifest-tmp.json > build/manifest-tmp.json
            jq --arg VERSION "$(git describe --tags)" '.version = $VERSION' build/manifest-tmp.json > build/manifest-tmp.json
            mv build/manifest-tmp.json build/manifest.json
      - run:
          name: Build extension zip
          command: mkdir -p dist && cd build && zip -r ../dist/extension.zip *
      - persist_to_workspace:
          root: dist
          paths:
            - extension.zip

  publish:
    docker:
      - image: cibuilds/chrome-extension:latest
    environment:
      - APP_ID: emaioeinhnifhcmlihcbooknbpjdbllb
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish to the Google Chrome Store"
          command: publish /tmp/workspace/extension.zip
